[package]
name = 'pallet-ibc'
version = "3.0.0-pre.0"
authors = ['Octopus Network <hi@oct.network>']
edition = '2021'
license = "Apache-2.0"
homepage = "https://oct.network"
repository 	= "https://github.com/octopus-network/substrate-ibc/"
description = "An IBC implementation on Substrate."
readme = "README.md"
build = 'build.rs'

[workspace]
members = [
	"ibc-applications/ics20-transfer",
	"ibc-support",
]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies.substrate-wasm-builder]
branch = 'polkadot-v0.9.28'
git = 'https://github.com/paritytech/substrate.git'

[dependencies]
#local crates
ibc-support = {version = "0.1.0", default-features = false, path = "./ibc-support" }
pallet-ics20-transfer = { version = "0.1.0", default-features = false, path = "./ibc-applications/ics20-transfer" }
# substate crates
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28", default-features = false }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28", default-features = false }
frame-benchmarking = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28", default-features = false, optional = true }
frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28", default-features = false }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28", default-features = false }
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28", default-features = false }
sp-tracing = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28", default-features = false }
# third-party libraries
log = { version = "0.4.0", default-features = false }
prost-types = { version = "0.11", default-features = false }
prost = { version = "0.11", default-features = false }
serde_json = { version = "1.0", default-features = false }
serde = { version = "1.0", default-features = false }
flex-error = { version = "0.4.4", default-features = false }
hex = {version = "0.4.0", default-features = false }
time = { version = ">=0.3.0, <0.3.12", default-features = false, features = ["macros", "parsing"] }
## for ibc protocl
ibc = { version = "0.19.0", default-features = false, branch = "dev", git = "https://github.com/octopus-network/cosmos-ibc-rs.git" }
ibc-proto = { version = "0.20", default-features = false }
tendermint-proto = { version = "=0.25.0", default-features = false }
beefy-light-client = { git = "https://github.com/octopus-network/beefy-light-client.git", branch = "main", default-features = false }

[dev-dependencies]
#local crates
pallet-ics20-transfer = { version = "0.1.0", path = "./ibc-applications/ics20-transfer" }
#thrid party crates
hex = '0.4.0'
sha2 = '0.10.2'
serde = "1.0"
chrono = "0.4.19"
# ibc protocol crates
ibc = { version = "0.19.0", branch = "dev", git = "https://github.com/octopus-network/cosmos-ibc-rs.git" }
# substrate crates
sp-io = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28"}
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28" }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28" }
sp-keyring = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28" }
frame-support = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28" }
pallet-assets = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28" }
pallet-balances = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28" }
pallet-babe = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28"}
sp-version = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28"}
sp-core = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28"}

[features]
default = ['std']
std = [
	"ibc-support/std",
	"codec/std",
	"log/std",
	"scale-info/std",
	"frame-benchmarking/std",
	"frame-support/std",
	"frame-system/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"sp-io/std",
	"sp-tracing/std",
	"prost-types/std",
	"prost/std",
	"ibc/std",
	"ibc-proto/std",
	"beefy-light-client/std",
	"serde_json/std",
	"serde/std",
	"flex-error/std",
	"hex/std",
	"time/std",
	"pallet-ics20-transfer/std"
]
runtime-benchmarks = ["frame-benchmarking"]
try-runtime = ["frame-support/try-runtime"]

[patch.crates-io]
ibc-proto = { git = "https://github.com/cosmos/ibc-proto-rs" }