[package]
name = "ibc-support"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# ibc crates
ibc = { git = "https://github.com/octopus-network/ibc-rs.git", branch = "dev", default-features = false }
ibc-proto = { git = "https://github.com/octopus-network/ibc-rs.git", branch = "dev", default-features = false }

# substrate crates
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch = "polkadot-v0.9.28", default-features = false }


[features]
default = ['std']
std = [
    "ibc/std",
    "ibc-proto/std",
    "codec/std",
    "scale-info/std",
    "sp-runtime/std",
]
